from tkinter import *
def simultaneous_equation_solver():
    sim = Tk()
    sim.title("SIMULTANEOUS EQUATION SOLVER")
    sim.config(bg="yellow")
    sim.geometry("650x525")
    L1 = Label(sim, text="Simultaneous equation solver", font=("Arial", 25), bg="yellow")
    L1.pack()

    def two_variable():
        def clear1():
            E1.delete(0, END)
            E2.delete(0, END)
            E3.delete(0, END)
            E4.delete(0, END)
            E5.delete(0, END)
            E6.delete(0, END)
        L2 = Label(sim, text="2 Variables: ", font=("Arial",25), bg="yellow")
        L2.place(x=10,y=40)
        L3 = Label(sim, text="First equation:             x +        y = ", font=("Arial",20), bg="yellow")
        L3.place(x=10,y=90)
        E1 = Entry(sim,width=3, font=("Arial",20))
        E1.place(x=230,y=90)
        E2 = Entry(sim,width=3, font=("Arial",20))
        E2.place(x=330,y=90)
        E3 = Entry(sim,width=3, font=("Arial",20))
        E3.place(x=445,y=90)
        L3 = Label(sim, text="Second equation:        x +        y = ", font=("Arial",20), bg="yellow")
        L3.place(x=10,y=130)
        E4 = Entry(sim,width=3, font=("Arial",20))
        E4.place(x=230,y=130)
        E5 = Entry(sim,width=3, font=("Arial",20))
        E5.place(x=330,y=130)
        E6 = Entry(sim,width=3, font=("Arial",20))
        E6.place(x=445,y=130)
        def simultaneous_eqsolver():
            a1 = int(E1.get())
            a2 = int(E4.get())
            b1 = int(E2.get())
            b2 = int(E5.get())
            c1 = int(E3.get())
            c2 = int(E6.get())
            D = (a1 * b2) - (a2 * b1)

            try:
                x = ((c1 * b2) - (c2 * b1)) / D
                y = ((a1 * c2) - (a2 * c1)) / D
                Lab = Label(sim, text=f"x = {x}, y = {y} ", font=("Arial",20), bg="yellow")
                Lab.place(x=10,y=220)
            except ZeroDivisionError:
                L3 = Label(sim, text="Error in the equation", font=("Arial",20), bg="yellow")
                L3.place(x=10,y=220)
        button1 = Button(sim, text="Submit", font=("Arial",10), padx=10, pady= 10, command=simultaneous_eqsolver)
        button1.place(x=50, y=170)
        button2 = Button(sim, text="clear", font=("Arial",10), padx=10, pady= 10, command=clear1)
        button2.place(x=150, y=170)
    two_variable()
    def three_variable():
        def clear1():
            E1.delete(0, END)
            E2.delete(0, END)
            E3.delete(0, END)
            E4.delete(0, END)
            E5.delete(0, END)
            E6.delete(0, END)
            E7.delete(0, END)
            E8.delete(0, END)
            E9.delete(0, END)
            E10.delete(0, END)
            E11.delete(0, END)
            E12.delete(0, END)

        L2 = Label(sim, text="3 Variables: ", font=("Arial", 25), bg="yellow")
        L2.place(x=10, y=250)
        L3 = Label(sim, text="First equation:             x +        y +        z = ", font=("Arial",20), bg="yellow")
        L3.place(x=10, y=300)
        E1 = Entry(sim, width=3, font=("Arial",20))
        E1.place(x=230, y=300)
        E2 = Entry(sim, width=3, font=("Arial",20))
        E2.place(x=330, y=300)
        E3 = Entry(sim, width=3, font=("Arial",20))
        E3.place(x=430, y=300)
        E4 = Entry(sim, width=3, font=("Arial",20))
        E4.place(x=545, y=300)
        L3 = Label(sim, text="Second equation:        x +        y +        z = ", font=("Arial",20), bg="yellow")
        L3.place(x=10, y=340)
        E5 = Entry(sim, width=3, font=("Arial",20))
        E5.place(x=230, y=340)
        E6 = Entry(sim, width=3, font=("Arial",20))
        E6.place(x=330, y=340)
        E7 = Entry(sim, width=3, font=("Arial",20))
        E7.place(x=430, y=340)
        E8 = Entry(sim, width=3, font=("Arial", 20))
        E8.place(x=545, y=340)
        L4 = Label(sim, text="Third equation:            x +        y +        z = ", font=("Arial", 20), bg="yellow")
        L4.place(x=10, y=380)
        E9 = Entry(sim, width=3, font=("Arial", 20))
        E9.place(x=230, y=380)
        E10 = Entry(sim, width=3, font=("Arial", 20))
        E10.place(x=330, y=380)
        E11= Entry(sim, width=3, font=("Arial", 20))
        E11.place(x=430, y=380)
        E12 = Entry(sim, width=3, font=("Arial", 20))
        E12.place(x=545, y=380)
        def simultaneous_eqsolver():
            a1 = int(E1.get())
            a2 = int(E5.get())
            a3 = int(E9.get())
            b1 = int(E2.get())
            b2 = int(E6.get())
            b3 = int(E10.get())
            c1 = int(E3.get())
            c2 = int(E7.get())
            c3 = int(E11.get())
            d1 = int(E4.get())
            d2 = int(E8.get())
            d3 = int(E12.get())

            D = a1 * (b2 * c3 - c2 * b3) - b1 * (a2 * c3 - c2 * a3) + c1 * (a2 * b3 - a3 * b2)

            try:
                x = round((d1 * (b2 * c3 - c2 * b3) - b1 * (d2 * c3 - c2 * d3) + c1 * (d2 * b3 - d3 * b2)) / D,3)
                y = round((a1 * (d2 * c3 - c2 * d3) - d1 * (a2 * c3 - c2 * a3) + c1 * (a2 * d3 - a3 * d2)) / D, 3)
                z = round((a1 * (b2 * d3 - d2 * b3) - b1 * (a2 * d3 - d2 * a3) + d1 * (a2 * b3 - a3 * b2)) / D, 3)

                Lab = Label(sim, text=f"x = {x}, y = {y}, z = {z}", font=("Arial",20), bg="yellow")
                Lab.place(x=10,y=470)
            except ZeroDivisionError:
                L3 = Label(sim, text="Error in the equation", font=("Arial",20), bg="yellow")
                L3.place(x=10,y=470)
        button1 = Button(sim, text="Submit", font=("Arial",10), padx=10, pady= 10, command=simultaneous_eqsolver)
        button1.place(x=50, y=420)
        button2 = Button(sim, text="clear", font=("Arial",10), padx=10, pady= 10, command=clear1)
        button2.place(x=150, y=420)
    three_variable()
    sim.mainloop()
